/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5a339ee0-33b4-4743-802e-44df555ed8af",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_swxpHdA9s",
    "aws_user_pools_web_client_id": "263ofmvea0d5cb2g1lo4engh2o",
    "oauth": {}
};


export default awsmobile;
