/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5a339ee0-33b4-4743-802e-44df555ed8af",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_swxpHdA9s",
    "aws_user_pools_web_client_id": "263ofmvea0d5cb2g1lo4engh2o",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ynu7kvhvzjbj5lsai4oeva3xii.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ytsq5wu22bhnrm4shuckuaq7za"
};


export default awsmobile;
